name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy on Cloudflare
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: npm i @cloudflare/wrangler && npx wrangler publish
